
const SNAKE_TEST_CONFIG = {
  TESTING_BOARD_COLOR: 0,
  TESTING_BOARD_INDEX: 2,
  TESTING_SECONDS_COUNT_DOWN: 1,    // constant SECONDS_COUNT_DOWN = 3
  TESTING_TIME_OUT_SECONDS: 30      // constant TIME_OUT_SECONDS = 3600
}

export default SNAKE_TEST_CONFIG
